### ISSUE TITLE
offset in search -sexp seems to be the beginning of the line position, not the beginning of the match position

### ISSUE THREAD

**Issue by jkitchin** [zot/microfts#3]
Whenever I use `(goto-char offset)` it appears that (point) is at the beginning of the line where the match occurred.

**Comment by zot** [comment]
Added the match offset, format is now

    ((FILE (POS LINE OFFSET chunk) ... ) ... )
        POS is the 1-based character position of the chunk in the file
        LINE is the 1-based line of the chunk in the file
        OFFSET is the 0-based offset of the first match in the chunk
