### ISSUE TITLE
Move Ivy support to its own package.

### ISSUE THREAD

**Issue by progfolio** [zot/microfts#8]
It's better to implement as much as possible using Emac's default completion interface.
Ivy (or any other) completion specific code should be it's own package. e.g. `ivy-microfts` or `helm-microfts`

**Comment by zot** [comment]
If Emacs has a completion interface that can act like ivy does in the screencast, I'm happy to look at it. I didn't think Emacs had something that would display lines of text like this.

**Comment by zot** [comment]
Checking out completion-at-point and its cousins...

**Comment by zot** [comment]
Did this
